spring:
  application:
    name: devdiarybackend

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        # Ensure schema and search_path are respected in Postgres
        default_schema: public

  datasource:
    # These should be provided via environment variables in deployment.
    # Use H2 as default fallback for local dev unless POSTGRES_URL is present.
    url: ${POSTGRES_URL:jdbc:h2:mem:devdiary;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH}
    username: ${POSTGRES_USER:sa}
    password: ${POSTGRES_PASSWORD:}
    driver-class-name: ${DB_DRIVER:org.h2.Driver}

  h2:
    console:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

# JWT configuration (do not hardcode secrets)
devdiary:
  jwt:
    secret: ${DEV_DIARY_JWT_SECRET:change-me}
    ttl-seconds: ${DEV_DIARY_JWT_TTL_SECONDS:86400}
